### ISSUE TITLE
feature request: RSS feed

### ISSUE THREAD

**Issue by bo0tzz** [vereis/blog_old#1]
I think I had your old blog in my feed reader. I'm mostly putting this request here so I don't forget to add this one once there's support ;)

**Comment by vereis** [comment]
Ahoy! Thanks for catching that -- the old blog was running on a much older version of Phoenix and they changed how views & rendering non-HTML templates work so I was putting this off!

Just implemented something quickly; please let me know if it works (deploying rn, give it a few min).

You should be able to see it here: https://vereis.com/rss

Please pardon the lazy descriptions for the mean time, I didn't want to shove the whole post body in there, or manually write summaries for every post right this moment.

I'm going to play around with some text summarization models though :-)

**Comment by bo0tzz** [comment]
Works a treat, thank you!
